name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v4.1.1
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          mikeon/recruitinator-frontend
          mikeon/recruitinator-frontend:$(date +'%Y-%m-%d')
