name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: frontend
      #run: docker build -t recruitinator-frontend . --tag my-image-name:$(date +%s)
      run: docker build -t recruitinator-frontend -t recruitinator-frontend:$(date +'%Y-%m-%d') .

